### ISSUE TITLE
Interceptor only provide rtp.Packet based API, some users want to deal with []byte

### ISSUE THREAD

**Issue by Sean-Der** [pion/interceptor#14]
@OrlandoCo just discovered this issue in [pion/webrtc](https://github.com/pion/webrtc/pull/1582) currently if a user does `Read` (not `ReadRTP`) it will skip the interceptors entirely.

Currently Interceptors deal entirely in rtp.Packet so `pion/webrtc` so we just don't use them in this case. We have the following choices. We have three different things we could do.

### Provide the ability to write `rtp.Packet`, `rtcp.Packet` and `[]byte`
Each Interceptor would provide the ability to do both. 

### Move to a `[]byte` based API
Instead of dealing with `rtp.Packet` in the public API everything will be `[]byte` based.

### Keep the current API
No changes

-----
These are my random thoughts as of today.

* If we switch to `[]byte` Interceptors will have to parse multiple times
  - Is this actually a problem, how expensive is parsing?
* If we switch to `[]byte` we can drop the dependency on `pion/rtcp` and `pion/rtp`
 - Do people care about this?
* Having multiple paths means more bugs/code to maintain

In pion/webrtc in the short term I propose switching `Read` to be fed via `Unmarshal` from `ReadRTP`. The extra operations are really unfortunate, but it unblocks the issue today.

**Comment by Sean-Der** [comment]
@at-wat @masterada Any thoughts on how this should go? We just offer `Read` and `ReadRTP` in pion/webrtc, so how do we design a `pion/interceptor` to support that best.

**Comment by masterada** [comment]
Copied from the other thread:
I left the simple Read out intentionally, because of the complexity they introduce:
A typical inteceptor will check the packet ssrc, read some extension info, maybe even peek into the payload. If there is a simple Read method it would mean that interceptors either:
a. Implement it, which means partially parsing the header in every interceptor, which might mean a worse performance implication than parsing the packet once. It also introduces a lot of complexity to the interceptor. 
b. Choose NOT to implement it, which would be more confusing than not supporting it in the first place.

In case of write it's even worse, because write interceptors may add extensions, which changes the header size, so the payload offset changes, so the packet payload must be copied into a new slice after the longer header.

My idea waa to leave the raw Read/Write for advanced use cases, but in those cases interceptors would not run. I tried to reflect this in the webrtc function docs, and obviously failed.

Can you describe the use case for this, and the reason raw Read is needed intead of ReadRTP? (if you just link the related code that would he helpful too).

Maybe we can do some softer parse before the interceptor chain that has better performance? Or some kind of alternate Packet type thats a slice, but with helper methods for header fields? I will keep thinking.

**Comment by masterada** [comment]
I think using both is  the worst option. I vote for either
- using RTP as is now,
- or using `type RTPPacket []byte` with methods for header fields

Although I think overall performance will be worse in the second case, especially with writes (because of the payload copy on adding extension) 

I would love to hear use cases for using the []byte methods.

**Comment by OrlandoCo** [comment]
@masterada We are currently moving the ion buffer to an interceptor to make it pluglabe for others services like `ion-avp` since ion is a SFU, performance is a key for the project. In the future the buffer will only receive byte slices to reduce allocation, since every `readRTP` will allocate a new byte slice on every read.

Also make an intereceptor with less features and some gotchas like `Read` and interceptor not being compatible may cause a lot problems in the future for newcomers or people who is not following in detail the new features.

The use case for `[]byte` is in the future preallocate  byte slices for packets to reduce allocations and garbage collection.

**Comment by masterada** [comment]
I see, thanks. 

What if we used Read instead of ReadRTP then, but parsed the header in advance and store it as an attribute? Or we could add an interceptor that parses the header and stores it as an attribute, then the other interceptors can use it.

Still thinking how these could work for write. @OrlandoCo do you use Write() as well, or do you use WriteRTP for that?

**Comment by Sean-Der** [comment]
That is a really cool idea of `HeaderParser` as an interceptor! I am inpartial to that, or always parsing the header. 

I do think `Read` and `ReadRTP` both need to run through the interceptor. Users will choose one for performance or ergonomics reason. I think they will be suprised that the default interceptors aren't being executed.

**Comment by OrlandoCo** [comment]
`Write` just unmarshal the slice and call internally `WriteRTP` (later I will see if this can be optimized), we can make the default to use the byte slice.

I would prefer interceptors not being opinionated. So if you are developing an intereceptor chain  maybe you can pass the unmarshaled rtp packet/header as an attribute but not forced to do that, but standarize the way it should be passed on the chain would be great.

@Sean-Der maybe on interceptor build we can check that all remote stream binding are of the same type, so they cant not being mixed, or leave just one kind

**Comment by masterada** [comment]
> HeaderParser is good inspiration though. For others reading the code I think that would inspire/demonstrate the power more of chaining interceptors.

Only problem with header parser is you can't expect it to always be there, so when callin ReadRTP, header might be parsed twice. On the other hand, with the lazy loading, you can call GetHeader in ReadRTP after the interceptor chain run, so you only parse the header once.

> I do think Read and ReadRTP both need to run through the interceptor. Users will choose one for performance or ergonomics reason. I think they will be suprised that the default interceptors aren't being executed.

What I suggest is this:
- user -> call Read:
   - call interceptor chain, which calls internal read, return the result
- user -> call ReadRTP:
   - call interceptor chain, which calls internal read
   - unmarshal the result, then return it as an rtp packet

This way both methods would run through interceptors, but you only need to implement one inside the interceptor.

**Comment by OrlandoCo** [comment]
> What I suggest is this:
> 
> * user -> call Read:
>   
>   * call interceptor chain, which calls internal read, return the result
> * user -> call ReadRTP:
>   
>   * call interceptor chain, which calls internal read
>   * unmarshal the result, then return it as an rtp packet
> 
> This way both methods would run through interceptors, but you only need to implement one inside the interceptor.

My PR currently do that

**Comment by masterada** [comment]
> 
> 
> > What I suggest is this:
> > 
> > * user -> call Read:
> >   
> >   * call interceptor chain, which calls internal read, return the result
> > * user -> call ReadRTP:
> >   
> >   * call interceptor chain, which calls internal read
> >   * unmarshal the result, then return it as an rtp packet
> > 
> > This way both methods would run through interceptors, but you only need to implement one inside the interceptor.
> 
> My PR currently do that

No, in your PR there are two methods in the interceptor:
```
	// BindRemoteStream lets you modify any incoming RTP packets. It is called once for per RemoteStream. The returned method
	// will be called once per rtp packet.
	BindRemoteStream(info *StreamInfo, reader RTPReader) RTPReader

	// BindRemoteRawStream lets you modify any incoming RTP raw packets. It is called once for per RemoteStream. The returned
	// method will be called once per rtp packet.
	BindRemoteRawStream(info *StreamInfo, reader RTPRawReader) RTPRawReader
```

What i'm talking about, is only 1 method in interceptor, but both track_remote.Read and track_remote.ReadRTP would use it.

**Comment by OrlandoCo** [comment]
@masterada I mean on webrtc readRTP calls interceprtor rawRead, I made two methods in the interceptor because I was not sure wichc approach to take

**Comment by masterada** [comment]
Oh i see, then I think we are talking about the same thing, just to make sure, this is how ReadRTP would work (see how it calls the raw reader as well):

```
// ReadRTP is a convenience method that wraps Read and unmarshals for you.
// It also runs any configured interceptors.
func (t *TrackRemote) ReadRTP() (*rtp.Packet, error) {
	b := make([]byte, receiveMTU)
	i, _, err := t.interceptorRawReader.Read(b)
	if err != nil {
		return nil, err
	}

	r := &rtp.Packet{}
	if err := r.Unmarshal(b[:i]); err != nil {
		return nil, err
	}

	return r, nil
}
```

**Comment by masterada** [comment]
Still, write is problematic, if the interceptor handles the whole packet as []byte, it would be very hard to change the header (eg: add extension), because the payload offset may change, which means copying the whole payload.

**Comment by OrlandoCo** [comment]
> Still, write is problematic, if the interceptor handles the whole packet as []byte, it would be very hard to change the header (eg: add extension), because the payload offset may change, which means copying the whole payload.

Im not planning to use the write interceptor so not sure about that.

**Comment by masterada** [comment]
Maybe we should leave RTPWriter interface as is? Or modify it a bit to better match WriteRTP in TrackLocalWriter? `Write(header *rtp.Header, payload []byte, attributes Attributes) (int, error)`

Either way it's quite ugly that Read uses raw []byte, but write uses header + payload, but I can't think of anything now for write. I'm going to sleep on this :)

**Comment by Sean-Der** [comment]
@masterada I am in favor of leaving `Write` as is! Unfortunate that they aren't symetric, but no reason that they need to be.

Since we aren't implementing an stdlib interface we could do things however we link!

**Comment by Sean-Der** [comment]
@OrlandoCo @masterada Maybe we could update `ReadRTP()` to let the user pass the buffer in?

We could make it optional also (pass nil to have Pion allocated for you)

**Comment by Sean-Der** [comment]
Personally I am really like @masterada suggestion of `rtp.Packet` out, `[]byte` in. That leaves the least performance on the table.

Then we can do the lazy loading of values from Attributes, and that covers everything :)

**Comment by OrlandoCo** [comment]
@Sean-Der I support both scenarios you suggested

**Comment by Sean-Der** [comment]
@OrlandoCo awesome!

@masterada You have any opinions/suggestions? I am happy to take on the dev work here :) This is the only thing on my `/v3` radar. After we get NACK in and API makes sense we are calling it our Christmas release 🥳

**Comment by Sean-Der** [comment]
I am gonna grab this tomorrow! Going to do `[]byte` out and `rtp.Packet` in.
