### ISSUE TITLE
totalLost count error in receiverStream?

### ISSUE THREAD

**Issue by Marco-LIU** [pion/interceptor#157]
in interceptor/receiver_stream.go

`func (stream *receiverStream) setReceived(seq uint16) {
	pos := seq % stream.size
	stream.packets[pos/64] |= 1 << (pos % 64)
}

func (stream *receiverStream) delReceived(seq uint16) {
	pos := seq % stream.size
	stream.packets[pos/64] &^= 1 << (pos % 64)
}

func (stream *receiverStream) getReceived(seq uint16) bool {
	pos := seq % stream.size
	return (stream.packets[pos/64] & (1 << (pos % 64))) != 0
}`

In there 3 functions, pos always in range [0, 128), thus pos/64 always in [0, 1). 
So, it only record recent 128 packages, may get error data in totalLost

If it not a bug, just IGNORE this.

**Comment by adriancable** [comment]
Yes, I think you are right. If the RTCP RR interval is more than 128 packets, we may under-report lost packets in the RR. The solution is probably to increase the size to something much larger (maybe 10X larger).

**Comment by adriancable** [comment]
@davidzhao / @Sean-Der - would be interested in your opinion on this. It seems to me that 128 is simply 'much too small' (since the RTCP RR interval is usually longer than 128 packets) and since things like the decision whether to include FEC in Opus packets rely on an accurate lost packet count, it appears that this should be fixed. But I wanted to make sure I am not missing something here.

**Comment by kcaffrey** [comment]
It appears to me from reading the code that each element in `stream.packets` doesn't represent a packet, but instead is a bitmask of 64 packets. That means the history is 8192 packets long. That should probably be enough for most cases, though it could be improved just in case the RR interval is very high or the packet rate is very high; I'm not certain there is any protection around those edge cases. Thankfully, they should be VERY rare.

**Comment by kcaffrey** [comment]
I'm going to write a test to verify the bug, then make sure my proposed fix works. If it does, I'll submit a PR

**Comment by adriancable** [comment]
Hi @kcaffrey - unless I've misunderstood (not uncommon!) aren't what you're saying and what I'm saying isomorphic to each other? The difference since seems to be in what the units of `stream.size` are 'meant to be', which isn't documented.

If the units of `stream.size` are 'meant to be packets', then the bug is that `stream.size` is much smaller than the typical RTCP RR interval. (my interpretation)

If the units of `stream.size` are 'meant to be blocks of 64 packets' then the bug is that `pos := seq % stream.size` is not the right calculation. (your interpretation)
